(Issue #2) Correct env var use.

diff --git a/.github/workflows/test-pypkg.yml b/.github/workflows/test-pypkg.yml
--- a/.github/workflows/test-pypkg.yml
+++ b/.github/workflows/test-pypkg.yml
@@ -43,17 +43,20 @@ jobs:
       uses: actions/checkout@v4
     - name: Install autotools
       run: |
-        if   [ "${{ runner.os }}" = "macos-12" ]; then
+        if   [ "${{ matrix.os }}" = "macos-12" ]; then
             brew install autoconf
             brew install autoconf-archive
             brew install automake
             brew install libtool
-        elif [ "${{ runner.os }}" = "macos-13" ]; then
+        elif [ "${{ matrix.os }}" = "macos-13" ]; then
             brew install autoconf-archive
             brew install automake
-        else
+        elif [ "${{ runner.os }}" = "Linux" ]; then
             sudo apt-get update
             sudo apt-get -y install autoconf-archive
+        else
+            echo "Invalid runner or OS"
+            exit 1
         fi
     - name: Install ${{ matrix.mpi_impl }}
       run: |
