(Issue #6) Reset GH test actions to full and correct setups.
All intentional breaks did indeed break as expected.

diff --git a/.github/workflows/test_py_sdist.yml b/.github/workflows/test_py_sdist.yml
--- a/.github/workflows/test_py_sdist.yml
+++ b/.github/workflows/test_py_sdist.yml
@@ -20,9 +20,10 @@ jobs:
     runs-on: ${{ matrix.os }}
     strategy:
       matrix:
-        os: [ubuntu-24.04]
-        mpi_impl: ["openmpi"]
-        python-version: ["3.13"]
+        os: [macos-13, macos-14, macos-15,
+             ubuntu-20.04, ubuntu-22.04, ubuntu-24.04]
+        mpi_impl: ["openmpi", "mpich"]
+        python-version: ["3.9", "3.10", "3.11", "3.12", "3.13"]
         exclude:
           # MPICH+Ubuntu24.04 tests presently fail because they detect only one
           # MPI process instead of two.  I suspect that this is related to using
@@ -42,28 +43,28 @@ jobs:
     ##-- Setup Testing Environment
     - name: Checkout OpenBTMixing
       uses: actions/checkout@v4
-    #- name: Install ${{ matrix.mpi_impl }}
-    #  run: |
-    #    if   [ "${{ runner.os }}" = "Linux" ]; then
-    #       sudo apt-get update
-    #       if   [ "${{ matrix.mpi_impl }}" = "openmpi" ]; then
-    #          sudo apt-get -y install openmpi-bin libopenmpi-dev
-    #       elif [ "${{ matrix.mpi_impl }}" = "mpich" ]; then
-    #          sudo apt-get -y install mpich libmpich-dev
-    #       else
-    #          echo "Cannot install ${{ matrix.mpi_impl }} for Linux"
-    #          exit 1
-    #       fi
-    #    elif [ "${{ runner.os }}" = "macOS" ]; then
-    #       if   [ "${{ matrix.mpi_impl }}" = "openmpi" ]; then
-    #          brew install open-mpi
-    #       elif [ "${{ matrix.mpi_impl }}" = "mpich" ]; then
-    #          brew install mpich
-    #       else
-    #          echo "Cannot install ${{ matrix.mpi_impl }} for macOS"
-    #          exit 1
-    #       fi
-    #    fi
+    - name: Install ${{ matrix.mpi_impl }}
+      run: |
+        if   [ "${{ runner.os }}" = "Linux" ]; then
+           sudo apt-get update
+           if   [ "${{ matrix.mpi_impl }}" = "openmpi" ]; then
+              sudo apt-get -y install openmpi-bin libopenmpi-dev
+           elif [ "${{ matrix.mpi_impl }}" = "mpich" ]; then
+              sudo apt-get -y install mpich libmpich-dev
+           else
+              echo "Cannot install ${{ matrix.mpi_impl }} for Linux"
+              exit 1
+           fi
+        elif [ "${{ runner.os }}" = "macOS" ]; then
+           if   [ "${{ matrix.mpi_impl }}" = "openmpi" ]; then
+              brew install open-mpi
+           elif [ "${{ matrix.mpi_impl }}" = "mpich" ]; then
+              brew install mpich
+           else
+              echo "Cannot install ${{ matrix.mpi_impl }} for macOS"
+              exit 1
+           fi
+        fi
     - name: Set up Python ${{ matrix.python-version }}
       uses: actions/setup-python@v5
       with:
