(Issue #6) Continue cleaning GC actions.

diff --git a/.github/workflows/test_py_sdist.yml b/.github/workflows/test_py_sdist.yml
--- a/.github/workflows/test_py_sdist.yml
+++ b/.github/workflows/test_py_sdist.yml
@@ -2,9 +2,6 @@ name: Test OpenBTMixing Python Source Distribution
 env:
   CLONE_PATH:   ${{ github.workspace }}
   PKG_ROOT:     ${{ github.workspace }}/openbtmixing_pypkg
-  VENV_PATH:    ${{ github.workspace }}/local/venv
-  MESON_VENV:   ${{ github.workspace }}/local/venv/meson
-  LOCAL_BIN:    ${{ github.workspace }}/local/bin
 on:
   push:
     branches:
@@ -36,38 +33,27 @@ jobs:
     #####----- SETUP TESTING ENVIRONMENT
     - name: Checkout OpenBTMixing
       uses: actions/checkout@v4
-    - name: Install meson dependencies
-      run: |
-        if   [ "${{ runner.os }}" = "macOS" ]; then
-            brew install ninja
-        elif [ "${{ runner.os }}" = "Linux" ]; then
-            sudo apt-get update
-            sudo apt-get -y install ninja-build
-        else
-            echo "Invalid runner or OS"
-            exit 1
-        fi
     - name: Install ${{ matrix.mpi_impl }}
       run: |
-          if   [ "${{ runner.os }}" = "Linux" ]; then
-             if   [ "${{ matrix.mpi_impl }}" = "openmpi" ]; then
-                sudo apt-get -y install openmpi-bin libopenmpi-dev
-             elif [ "${{ matrix.mpi_impl }}" = "mpich" ]; then
-                sudo apt-get -y install mpich
-             else
-                echo "Cannot install ${{ matrix.mpi_impl }} for Linux"
-                exit 1
-             fi
-          elif [ "${{ runner.os }}" = "macOS" ]; then
-             if   [ "${{ matrix.mpi_impl }}" = "openmpi" ]; then
-                brew install open-mpi
-             elif [ "${{ matrix.mpi_impl }}" = "mpich" ]; then
-                brew install mpich
-             else
-                echo "Cannot install ${{ matrix.mpi_impl }} for macOS"
-                exit 1
-             fi
-          fi
+        if   [ "${{ runner.os }}" = "Linux" ]; then
+           if   [ "${{ matrix.mpi_impl }}" = "openmpi" ]; then
+              sudo apt-get -y install openmpi-bin libopenmpi-dev
+           elif [ "${{ matrix.mpi_impl }}" = "mpich" ]; then
+              sudo apt-get -y install mpich
+           else
+              echo "Cannot install ${{ matrix.mpi_impl }} for Linux"
+              exit 1
+           fi
+        elif [ "${{ runner.os }}" = "macOS" ]; then
+           if   [ "${{ matrix.mpi_impl }}" = "openmpi" ]; then
+              brew install open-mpi
+           elif [ "${{ matrix.mpi_impl }}" = "mpich" ]; then
+              brew install mpich
+           else
+              echo "Cannot install ${{ matrix.mpi_impl }} for macOS"
+              exit 1
+           fi
+        fi
     - name: Set up Python ${{ matrix.python-version }}
       uses: actions/setup-python@v5
       with:
@@ -75,16 +61,9 @@ jobs:
     - name: Setup Python dependencies
       run: |
         $CLONE_PATH/.github/workflows/setup_base_python.sh ${{ runner.os }}
-    - name: Install latest meson
+    - name: Install Meson build system
       run: |
-        mkdir -p $VENV_PATH
-        python -m venv $MESON_VENV
-        . $MESON_VENV/bin/activate
-        python -m pip install --upgrade pip
-        python -m pip install meson>=1.6.0
-        mkdir -p $LOCAL_BIN
-        ln -s $MESON_VENV/bin/meson $LOCAL_BIN
-        echo "$LOCAL_BIN" >> "$GITHUB_PATH"
+        $CLONE_PATH/.github/workflows/install_meson.sh ${{ github.workspace }} ${{ runner.os }}
 
     ##-- Run full test suite
     # Prefer full end-to-end test of wheels rather than testing in local clone
